modLoader = "javafml" #mandatory
loaderVersion = "[43,)" #mandatory
license = "GNU_GPL.3"
issueTrackerURL = "https://github.com/warrentode/TodeVillagers/issues"

[[mods]]
modId = "todevillagers"
version = "${file.jarVersion}"
displayName = "Tode Villagers"
updateJSONURL = "https://raw.githubusercontent.com/warrentode/TodeVillagers/main/update.json"
displayURL = "https://github.com/warrentode/TodeVillagers"
logoFile = "logo.png"
credits = """
Special thanks to my sons, and my supporters: \
Marshal Nash and Trevor Brannigan, \
for supporting my blog and my various projects!
"""
authors = "Warren Tode (ToadieOdie)"
description = '''
This mod adds a variety of villagers with their trades to the game.
'''

[[dependencies.todevillagers]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.todevillagers]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.21)"
ordering = "NONE"
side = "BOTH"

[modproperties.todevillagers]
#catalogueItemIcon = "todevillagers:crushed_glass" #Support for Catalogue mod
#configuredBackground = "todevillagers:textures/block/glass_kiln_side.png" #Support for Configured mod