modLoader="javafml"
loaderVersion="[43,)"
license="GNU_GPL.3"
issueTrackerURL="https://github.com/toadie-odie/TodeVillagers/issues"
[[mods]]
modId="todevillagers"
version="1.19.2-0.2.1"
displayName="Tode Villagers"
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
displayURL="https://github.com/toadie-odie/TodeVillagers"
logoFile="logo.png"
credits="Special thanks to my sons, and my supporters: Marshal Nash and Trevor Brannigan, for supporting my blog and my various projects!"
authors="Warren Tode (ToadieOdie)"
description="This mod adds a variety of villagers with their trades to the game."

[[dependencies.todevillagers]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.todevillagers]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"

[modproperties.todevillagers]
    catalogueItemIcon="todevillagers:crushed_glass" #Support for Catalogue mod
    configuredBackground="todevillagers:textures/block/glass_kiln_side.png" #Support for Configured mod
